# Generated by Django 4.2.10 on 2024-02-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_alter_messages_location_alter_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
